### ISSUE TITLE
Add Support for Audio Files

### ISSUE THREAD

**Issue by ChokshiUtsav** [ChokshiUtsav/TagBasedFileSystem#1]
### Generate tags for audio files based on its meta-data.

**Comment by Deeksha117** [comment]
added metadata information of audio files for tag suggestions.

def findMetadataforMusic(filename): 
    tags = []  
    # 'album', 'album_artist', 'album_type', 'artist', 'artist_origin', 'artist_url', 'audio_file_url', 
    #'audio_source_url', 'best_release_date', 'bpm', 'cd_id', 'chapters', 'clear', 'comments', 
    # 'copyright_url', 'disc_num', 'encoding_date', 'extended_header', 'file_info', 'frame_set', 'frameiter', 
    #'genre', 'getBestDate', 'getTextFrame', 'header', 'images', 'internet_radio_url', 'isV1', 'isV2', 'lyrics',
    # 'objects', 'play_count', 'publisher', 'recording_date', 'release_date', 'save',
    # 'title', 'track_num', 'unique_file_ids',  'version'
    audiofile = eyed3.load(filename)
    if audiofile.tag.artist:
        artistlist = audiofile.tag.artist.replace(' ','-').split(',')
        tags.extend([artist for artist in artistlist])

    if audiofile.tag.album:
        album = audiofile.tag.album.replace(' ','-')
        tags.append(album)

    if audiofile.tag.album_artist:
        album_artist = audiofile.tag.album_artist.replace(' ','-')
        tags.append(album_artist)

    if audiofile.tag.recording_date and audiofile.tag.recording_date.year:
        tags.append(str(audiofile.tag.recording_date.year))

    if audiofile.tag.genre.name:
        genre = audiofile.tag.genre.name.replace(' ','-')
        tags.append(genre)
    return list(set(tags))
